### ISSUE TITLE
請問2014的資料串接的遠端連結預計何時會出來

### ISSUE THREAD

**Issue by vulcanlee** [MOPCON/MOPCON_WP8Apps#2]
與2013年的資料格式與網址，是否有甚麼不同或者多出來的功能需求

**Comment by CQD** [comment]
我這兩個禮拜弄出來 Orz

功能需求目前沒有變化，不過這件事情我猜要等 Call for Paper 結束議程組安排議程的時候才能真的確定...

**Comment by vulcanlee** [comment]
好的，那我就等您確認好最後資料，我在開始動工囉
